language: node_js
node_js:
  - "14"
script:
  - PROJECT_ROOT_PATH="$(pwd)"
  # Classical test workflow
  - npm run build
  - npm run test
  # Checking the bundle against commonjs and esm configurations
  ## Instead of linking on ., we pack the package as if it was released on npm registry
  ## then we link towards this version (no devDependencies installed, no unpublished files available...).
  - cd "$PROJECT_ROOT_PATH"
  - npm pack && mkdir -p bundle && tar -C bundle -zxvf jest-fast-check-*.tgz
  - rm -rf node_modules/
  ## CommonJS
  - cd "$PROJECT_ROOT_PATH"
  - cd test-bundle/commonjs && yarn && yarn test
  ## ESM - Not activated, need updates on https://github.com/facebook/jest/issues/9430
  #- cd "$PROJECT_ROOT_PATH"
  #- cd test-bundle/esm && yarn && yarn test
  ## Cleaning for deploy
  - cd "$PROJECT_ROOT_PATH"
deploy:
  provider: npm
  email: npm@dubien.org
  skip_cleanup: true
  api_key:
    secure: iWQm9gZ6OElKgMmeZ9kGVlOfqwu5hLMRu8527daekJn7tcuEEBnz2gDtbjIOo0pGmlEjyweaYMxcrCsey6r8TWnVkBs99ir0emlqINkuNQkEQ4QqyX15ayukJHPYMwBjyasdgT5V9e/W9kZgf5WGPZDwfhAxurtlig0KN6U9fuO43o6u7+KdJKg4iUoLu75rItz0eu15uhE6fMLpYRLS8ehD4KS4Vmw2wxe6j8fOtLsLQeEp4scawyrvutjARqSHDaB9OHGBvSSwU9P/m+POi3OP8HTlT584X+ty9Sabg7cyrgmnMsKjWfLi76OpgOhsUSlltcgfdmQ/Qf9n+I9Ap7AF5hETXa+8Jg/k0wE5o0DdQInVd48NBMXCYYztEK+pKVpW0kfI/aBGh0ZP2bqcvrNEXIOhy5rDdW3CbqgywSsgkfmo5Y7TYHNcEqDYMc7bwhep8Nqiqskienj1DV6MK3u1Kl1SU5qpIlrnd4bkfLt3J3PWxO9UgCAlJGwl3UfxRRmdpbdwr/ZxGFLI3EQohQzuo7b8lOnpCdHBivvqpUygWQ5s3Ui8QCp8SeEe/cKDe/RVYpVxZ/q/x04dV9e7F0SwN2aJx9G4KpyotEpo3sOL8vAroamrroT4ZvBnnx/d13rvuUoWok1daqi2i2Lxs3WvM/M0xAWhXG78u7JAqks=
  on:
    tags: true
    repo: dubzzz/jest-fast-check
