language: node_js
node_js:
  - "14"
script:
  - PROJECT_ROOT_PATH="$(pwd)"
  # Classical test workflow
  - npm run build
  - npm run test
  # Checking the bundle against commonjs and esm configurations
  ## Instead of linking on ., we pack the package as if it was released on npm registry
  ## then we link towards this version (no devDependencies installed, no unpublished files available...).
  - cd "$PROJECT_ROOT_PATH"
  - npm pack && mkdir -p bundle && tar -C bundle -zxvf jest-fast-check-*.tgz
  - rm -rf node_modules/
  ## CommonJS
  - cd "$PROJECT_ROOT_PATH"
  - cd test-bundle/commonjs && yarn && yarn test
  ## ESM - More on ESM + Jest at https://github.com/facebook/jest/issues/9430
  - cd "$PROJECT_ROOT_PATH"
  - cd test-bundle/esm && yarn && yarn test
  ## Cleaning for deploy
  - cd "$PROJECT_ROOT_PATH"
deploy:
  provider: npm
  email: npm@dubien.org
  skip_cleanup: true
  api_key:
    secure: MKuA+7/hWUh+XGHBnAgG89/hzjZsEv7cFFpoWgM0n8cxQJ+Xy14DiFt0KJX0UXW+HsG3S5afXfLWfMGmgVCrtxQAOVAF7lkRawXoYNKmUrZpPZtTsk3AWLkOiuiCsRSpgaR6/0BUgVTQtKDJVXmJUoiBOiOsXULRfLT6QrCPV3aozeP3T5TarN9vFhaR3Bjo7zU9TRv9EVNnFH3WbIm+Scvh+IvMdg53UfoR/bcLzJ8rykVZIO4WMLVMPqLck1xGejyiOEnaVpgzHfwB4koUAO9yIrsHqZ4qIr8CqtEBHRrAWgMBguI0xTkI+bdqUmGsXon0mRsHini3XhovnxYW48cIgxMdEVO/CGpUrppY6T3XljkZi8hy8qiM+S0mW8+BXU66P1bsr5rSWw0QCdLJvCqKWtE8FMu+i/ZjKefFxrD6QHlp+CL9SV9qUfUg1sAKcrtTY6LtSkdO8p4AsLNn5nD145ONqQdNnFNsgiAfLRiO0y+Ropp/Uqtc/QDxvuKgXqCzjAT9U66Pxo5lavkr44HPFS8iZgQzi+r73f20U1DyuvUtwWGtP/LfD8RnX64KAVNBF8zL+sDVClZkZ4LOHc046qHmpb3ATf2/Qu06f/6uuXOvHzttYiEd0j6ILUoD+XgCcQjyBP2po+CKQcmTD9ZvvVUREOwEn2poBBhdS9M=
  on:
    tags: true
    repo: dubzzz/jest-fast-check
