language: node_js
node_js:
  - "14"
script:
  - PROJECT_ROOT_PATH="$(pwd)"
  # Classical test workflow
  - npm run build
  - npm run test
  # Checking the bundle against commonjs and esm configurations
  ## Instead of linking on ., we pack the package as if it was released on npm registry
  ## then we link towards this version (no devDependencies installed, no unpublished files available...).
  - cd "$PROJECT_ROOT_PATH"
  - npm pack && mkdir -p bundle && tar -C bundle -zxvf jest-fast-check-*.tgz
  - rm -rf node_modules/
  ## CommonJS
  - cd "$PROJECT_ROOT_PATH"
  - cd test-bundle/commonjs && yarn && yarn test
  ## ESM - Not activated, need updates on https://github.com/facebook/jest/issues/9430
  #- cd "$PROJECT_ROOT_PATH"
  #- cd test-bundle/esm && yarn && yarn test
  ## Cleaning for deploy
  - cd "$PROJECT_ROOT_PATH"
deploy:
  provider: npm
  email: npm@dubien.org
  skip_cleanup: true
  api_key:
    secure: C0mcpe3g0oAmOJLRyl6JRVjTJt6S9t/WJb/+o3Zq0fegehi7c1gotY6jRg43VxaGPbruyyCA18SC3mF7ca5768wvW3gcHkVe1rFlchkzeFYJmSggcPwDQXpQVKO/M57ohAh92R5p+9MYFhxJcfZW5DDegwIdTqxaXKupFTFEeP/FNWBce35WZSqzH9rzmAJbuPXcRAJ9xEvoyv1ouSfjZ8hNBnB+FZUTLSdaKlQDN2riGYdTXyRrbzR9liGEYNr3oz1rC/ZCplwivKJz2gvb344G2IZHzzfLhCIsSWvi2v+j/lxK8Qz+PLOe4jA8U6lLe8phzFQah42BBvLJbdP8mpxZxSriYxLJme723HFr22ECDHVJbl0wTO5v9K4nfQPBq9wORlgOxcDT5AmrbSuEGDk3sTakmCsk2Vxo3vVjMytiBJzoPaSkEE9Rl3DdRdgiaxy1AA7Onb2INV08pz+5cbgshjuWdaF/4B/reDsSrXnNOahN23mJfKOw6X3Pb9jR91muERusYcipWeuEZ+t2zKFW5ZwbmPoszfdc0A9CtqpsJDJQpYwUirIMSqIg8KjUYEHCJaVUO16a33cECs+0SQLflA1v01U9WZmHDlsIzri1RyU1C/JHOS6mfI61iBDAoaw6sU6xHdCYMq9wPv+AhmEVKFeWoRLGN7uFLt0wM3g=
  on:
    tags: true
    repo: dubzzz/jest-fast-check
